# Generated by Django 5.1.3 on 2024-11-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('Fisico', 'Físico'), ('Digital', 'Digital')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.libro')),
            ],
        ),
    ]
